### ISSUE TITLE
无法自动填充规则

### ISSUE THREAD

**Issue by Laimeiyunzn** [oooldtoy/SSTAP_ip_crawl_tool#1]
1.0.9.7 版本，抓取到了规则 ，但是无法写入，自己手动输入摁Ctrl+C则会清除当前目录手动写入的规则。

**Comment by oooldtoy** [comment]
按理说抓取到一个ip之后，就会立即写入。按下ctrl+c之后脚本强制停止，也不会对之后手动写入的规则产生任何影响，除非之后又启动了脚本，那么就会覆盖以前的规则。

**Comment by NormanBB** [comment]
@Laimeiyunzn 

建议，如果有Python基础的话，可以在代码中加入print语句，查看程序运行状态，来解决问题。
