### ISSUE TITLE
服务器连接失败 报错

### ISSUE THREAD

**Issue by klrito123** [oooldtoy/SSTAP_ip_crawl_tool#10]
ip_crawl_toolv3.4
3.0版增加上传规则至服务器进行共享，如不想进行规则上传，请使用2.0版
快速版规则请访问 http://www.oldtoy.online/rules
请输入游戏进程名（可启动游戏后在任务管理器 进程 中查询）
如果有多个进程请使用英文逗号分隔开：archeage.exe
是否抓取udp协议ip，默认不抓取。
抓取udp协议ip需使用管理员权限运行，且需要开启windows防火墙，请确保使用管理员权限运行本程序和开启了防火请。
如需抓取udp协议请输入1:1
将检测以下程序
archeage.exe
请核对名称是否正确，如不正确请重新启动输入
请输入游戏英文名（按回车跳过）：archeage
请输入游戏中文名（按回车默认为['archeage.exe']），注意！这将影响到SSTAP显示的名称！：
正在检测['archeage.exe']远程ip,可随时关闭窗口停止终止程序。
现在你可以打开SSTAP全局，并启动游戏，发现的ip将会自动记录到当前目录的rules文件中
发现archeage.exe新ip--tcp
203.205.235.247
服务器连接失败
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "ip_crawl_tool.py", line 151, in update_data
OSError: [WinError 10057] 由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地址，发送或接收数据的请求没有被接受。

系统win10
坐标海外

**Comment by oooldtoy** [comment]
@klrito123 已解决，服务器挂了。不影响实际使用。
