### ISSUE TITLE
系统找不到路径怎么回事呢？

### ISSUE THREAD

**Issue by nickical** [oooldtoy/SSTAP_ip_crawl_tool#11]
ip_crawl_toolv4.0
是否抓取udp协议ip，默认不抓取。
抓取udp协议ip需使用管理员权限运行，且需要开启windows防火墙，请确保使用管理员权限运行本程序和开启了防火墙。
如需抓取udp协议请输入（udp）:udp
请选择写入文件模式
1.SSTAP
2.NETCH。
请输入1or2：1
1.手动输入进程
2.扫描文件夹
请输入1or2：2
请输入需要扫描的文件夹路径：C:\Program Files (x86)\Google\Chrome\Application
将检测以下程序
chrome_pwa_launcher.exe
elevation_service.exe
chrmstp.exe
setup.exe
notification_helper.exe
chrome.exe
chrome_proxy.exe
请核对名称是否正确，如不正确请重新启动输入
请输入游戏英文名（按回车跳过）：chrome.exe
请输入游戏中文名（按回车默认为['chrome_pwa_launcher.exe', 'elevation_service.exe', 'chrmstp.exe', 'setup.exe', 'notification_helper.exe', 'chrome.exe', 'chrome_proxy.exe']），注意！这将影响到SSTAP显示的名称！：chrome
正在检测['chrome_pwa_launcher.exe', 'elevation_service.exe', 'chrmstp.exe', 'setup.exe', 'notification_helper.exe', 'chrome.exe', 'chrome_proxy.exe']远程ip,可随时关闭窗口停止终止程序。
现在你可以打开全局，并启动游戏，发现的ip将会自动记录到当前目录的rules文件中
发现新ip chrome.exe--tcp
108.177.97.188
系统找不到指定的路径。

**Comment by oooldtoy** [comment]
@nickical 程序目录下有没有config.txt文件呢

**Comment by nickical** [comment]
@oooldtoy 首先感谢开发者抽空回复，config.txt文件是存在的，不清楚什么原因，又跑了一次相同测试，没问题了，抓到的IP均能正常写入rules。之前使用3.34版本用于抓取FIFA21的路由，一直停留在成功连接到服务器的光标就无反应，有空回家用4.0版本再次测试，如有问题，再回帖提问。

**Comment by oooldtoy** [comment]
@nickical 服务器已经没了，用4.0就好

**Comment by nickical** [comment]
经测试，4.0版本能正常使用，结帖。
