### ISSUE TITLE
希望可以支持顯示埠  通訊埠

### ISSUE THREAD

**Issue by ganwennl** [oooldtoy/SSTAP_ip_crawl_tool#13]
通訊埠大陸應該是叫端口，我不是拿來給sstap用，是抓一些其他的程式也很方便。

我有開發過此類抓取IP的軟體，顯示埠口很方便，希望能加入。

現成的有就不造輪子。^_^

雖然目前夠用。

**Comment by sdfsdfsdf145314364** [comment]
> 通訊埠大陸應該是叫端口，我不是拿來給sstap用，是抓一些其他的程式也很方便。
> 
> 我有用其它語言開發過此類抓取IP的軟體，顯示埠口很方便，應該就是幾行代碼的事情希望能加入。
> 
> 用這個主要是有現成的有就不造輪子。^_^
> 
> 雖然目前夠用。

**Comment by oooldtoy** [comment]
@sdfsdfsdf145314364 这个目前没有考虑，毕竟是用来给sstap使用的，没有这方面的需求。
