### ISSUE TITLE
SSTAP_ip_crawl_tool支持对有反作弊游戏的抓取吗，工具会被识别为外挂导致游戏封禁吗

### ISSUE THREAD

**Issue by huyongzhe2** [oooldtoy/SSTAP_ip_crawl_tool#14]
SSTAP_ip_crawl_tool支持对有反作弊游戏的抓取吗，工具会被识别为外挂导致游戏封禁吗
比如（CSGO，Valorant，APEX，LOL）

**Comment by oooldtoy** [comment]
@huyongzhe2 我对游戏的反外挂机制不太了解。不过这个工具只是使用了简单windows api和读取防火墙日志来实现ip获取的，不存在干预游戏和系统进程的问题，而且目前也没有收到类似的问题反馈。

**Comment by huyongzhe2** [comment]
@oooldtoy 那抓取时候开游戏加速器，加速这款游戏还能抓取到真实的IP吗

**Comment by oooldtoy** [comment]
@huyongzhe2 要看加速器使用的加速方式，有些方式可能无法抓取。具体的只能自己进行尝试。

**Comment by huyongzhe2** [comment]
@oooldtoy OK，谢谢你 这个工具帮了我大忙
