### ISSUE TITLE
关于是否需要开启加速器

### ISSUE THREAD

**Issue by Aliansea** [oooldtoy/SSTAP_ip_crawl_tool#16]
我想问一下抓取IP的时候是否需要开启游戏加速器？因为有些游戏不开游戏加速器的话是无法连接到服务器的。然后是开游戏加速器抓取的ip准确，还是不开游戏加速器抓取到的ip准确？

**Comment by oooldtoy** [comment]
@Aliansea 需要开启sstap加速

**Comment by Aliansea** [comment]
> @Aliansea 需要开启sstap加速

那是不是也需要开启游戏加速器，例如uu加速器之类的

**Comment by oooldtoy** [comment]
@Aliansea sstap能够加速就不需要用其他的，而且用其他的也不一定保证能够抓到

**Comment by Aliansea** [comment]
> @Aliansea sstap能够加速就不需要用其他的，而且用其他的也不一定保证能够抓到

那就是说，用uu加速器之类的软件加速游戏的话，抓去到的ip不一定准确或者抓不到，最好是用sstap全局加速后抓取游戏ip是吧。

**Comment by oooldtoy** [comment]
@Aliansea 是的

**Comment by Aliansea** [comment]
> @Aliansea 是的

好的，非常感谢😘
