### ISSUE TITLE
要是安卓端可以用就好了

### ISSUE THREAD

**Issue by jt8823** [oooldtoy/SSTAP_ip_crawl_tool#18]
谢谢!!!

**Comment by oooldtoy** [comment]
@jt8823 安卓端建议使用clash，然后分析日志。

**Comment by jt8823** [comment]
> @jt8823 安卓端建议使用clash，然后分析日志。

主要是个指定功能很好用,    clash的日志,也会出现很多其它app的  ip呀

**Comment by oooldtoy** [comment]
@jt8823 你把分应用代理只勾选你想检测的app。

**Comment by jt8823** [comment]
> @jt8823 你把分应用代理只勾选你想检测的app。


哦哦  我先一直用的V2RAYNG  我试试看  谢谢!!!
