### ISSUE TITLE
Feature Request: 多 exe 爬取，以及 CIDR Merge 处理

### ISSUE THREAD

**Issue by terryops** [oooldtoy/SSTAP_ip_crawl_tool#2]
1. 因为一般有各种启动器，然后还有游戏主程序
2. 现在抓的都是/32的 IP，显得非常冗长，而且扩展性不好。希望可以加入 netaddr 处理合并一下。

**Comment by terryops** [comment]
1. 因为一般有各种启动器，然后还有游戏主程序
2. 现在抓的都是/32的 IP，显得非常冗长，而且扩展性不好。希望可以加入 netaddr 处理合并一下。

**Comment by oooldtoy** [comment]
已更新
