### ISSUE TITLE
打开exe文件软件内显示参数错误并闪退

### ISSUE THREAD

**Issue by opteron18** [oooldtoy/SSTAP_ip_crawl_tool#5]
是否需要安装python环境？

**Comment by oooldtoy** [comment]
@opteron18 使用源代码运行需要安装python，打包好的exe不需要

**Comment by opteron18** [comment]
但是我的exe打开闪退




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "oooldtoy"<notifications@github.com&gt;; 
发送时间: 2019年12月1日(星期天) 上午10:58
收件人: "oooldtoy/SSTAP_ip_crawl_tool"<SSTAP_ip_crawl_tool@noreply.github.com&gt;; 
抄送: "Opteron"<965972181@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [oooldtoy/SSTAP_ip_crawl_tool] 打开exe文件软件内显示参数错误并闪退 (#5)




@opteron18 使用源代码运行需要安装python，打包好的exe不需要

**Comment by oooldtoy** [comment]
@opteron18 经过测试，在win7上运行3.0.1会报错，原因不明

**Comment by oooldtoy** [comment]
3.1以上版本已修复该类问题

**Comment by opteron18** [comment]
thank you






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "oooldtoy"<notifications@github.com&gt;; 
发送时间: 2019年12月10日(星期二) 中午11:51
收件人: "oooldtoy/SSTAP_ip_crawl_tool"<SSTAP_ip_crawl_tool@noreply.github.com&gt;; 
抄送: "Opteron"<965972181@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [oooldtoy/SSTAP_ip_crawl_tool] 打开exe文件软件内显示参数错误并闪退 (#5)




3.1以上版本已修复该类问题
