### ISSUE TITLE
python  报错

### ISSUE THREAD

**Issue by kaif546** [oooldtoy/SSTAP_ip_crawl_tool#9]
依赖都全装了，也没有开udp ，想知道是什么原因，谢谢大佬

  File "E:/dd/SSTAP_ip_crawl_tool-3.3.4/ip_crawl_tool.py", line 151, in update_data
    s.send(msg)
OSError: [WinError 10057] 由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地址，发送或接收数据的请求没有被接受。

**Comment by oooldtoy** [comment]
@kaif546 因为没有更新共享服务器的ip，所以连接不上。但是事实上不管这个报错就可以了。实在不想看可以使用以前不共享的版本

**Comment by oooldtoy** [comment]
已解决此问题，请下载3.4版本
